
server:
    port: 0
spring:
  cloud:
    config:
      profile: dev
  application:
    name: booking-microservice
#Define connection to mysql
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
#    username: root
#    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      application-name: ${spring.application.name}
    service-url:
      defaultZone: http://localhost:8761/eureka/eureka
resilience4j:
  circuitbreaker:
    instances:
      stock-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
    retry:
      instances:
        stock-service:
          max-attempts: 3
          wait-duration: 2s
          retry-exceptions:
            - feign.FeignException
            - java.io.IOException
    timelimiter:
      instances:
        stock-service:
          timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true