server:
  port: 8080
spring:
  application:
    name: api-gateway-microservice
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9991/realms/inamsay-microservices-real
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: sUsavPXZDM3qtDnb47RhSVs8ZBFhARhM
            provider: keycloak
            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
            scope: openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-MICROSERVICE
              predicates:
                - Path=/api/v1/category/**, /api/v1/products/**
              filters:
                - TokenRelay=
            - id: booking-service
              uri: lb://BOOKING-MICROSERVICE
              predicates:
                - Path=/api/v1/hello/**

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      application-name: ${spring.application.name}
    service-url:
      defaultZone: http://localhost:8761/eureka/eureka