server:
  port: 8080
spring:
  application:
    name: api-gateway-microservice
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-MICROSERVICE
              predicates:
                - Path=/api/v1/category/**, /api/v1/products/**
    #          filters:
    #            - TokenRelay=
            - id: booking-service
              uri: lb://BOOKING-MICROSERVICE
              predicates:
                - Path=/api/v1/hello/**

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      application-name: ${spring.application.name}
    service-url:
      defaultZone: http://localhost:8761/eureka/eureka